### ISSUE TITLE
Keep user feedback on pick page

### ISSUE THREAD

**Issue by MattGarfield** [predbrad/fabbit-iot#2]
When a user clicks the "Light it up" button, rather than changing to a new page with the text feedback 

"Check the light, the color you set was H:0.20833333333333334 S:1.0 V:0.8"

can we just add a text line to the picker page that says

"Current color is R: XXX, G: XXX, B: XXX"

and refresh the values in the XXX when a new color is chosen. 

That will allow the user to pick another color without having to refresh the picker page every time. Thanks!

**Comment by predbrad** [comment]
This is done.

**Comment by predbrad** [comment]
done
